package.json
just moving the tests framework over to the devDependencies
=> testing frameworks should be in the dev-dependecies

lib/protocols.js, spec/configs/domain.xml
Fix error message and adjust domain configuration.
=> HRJS-26 HRJS-34

README.md, lib/codec.js, lib/io.js, lib/protocols.js, package.json, spec-manual/infinispan_manual_stress_get_spec.js, spec-manual/infinispan_manual_stress_iterate_spec.js, spec/codec_spec.js, spec/configs/domain.xml, spec/protocols_spec.js
The testsuite looks good. 
The SSL tests are failing due to expired certificates. I'll address that so that they're created on the fly instead of being committed.
=> HRJS-54 Add more checks at read time to check if read can happen

spec/infinispan_local_spec.js, spec/utils/testing.js
https://issues.jboss.org/browse/HRJS-58
=> HRJS-58 Only wait for events to be received

lib/infinispan.js, lib/protocols.js, spec/infinispan_cluster_spec.js
https://issues.jboss.org/browse/HRJS-64
=> HRJS-64 Allow client to be configured with basic client intelligence

Jenkinsfile, Jenkinsfile-release, lib/infinispan.js, package.json
https://issues.jboss.org/browse/HRJS-66
=> HRJS-66 Jsdoc related fixes

README.md, lib/codec.js, lib/infinispan.js, lib/io.js, lib/protocols.js, run-domain.sh, run-testsuite.sh, smoke-tests.sh, spec/codec_spec.js, spec/configs/domain.xml, spec/configs/host.xml, spec/infinispan_json_spec.js, spec/infinispan_local_spec.js, spec/protocols_spec.js, spec/tests.js, spec/utils/testing.js
https://issues.jboss.org/browse/HRJS-35
https://issues.jboss.org/browse/HRJS-67
https://issues.jboss.org/browse/HRJS-68
Added support for transcoding so that both String and JSON can be supported natively. Also upgraded to Hot Rod protocol 2.8 and worked around a change in behaviour in server 9.4.
Do not integrate yet since it relies on server snapshot. 9.4.0.CR1 should include all the necessary fixes.
=> HRJS-35, HRJS-68 and HRJS-67

Jenkinsfile, Jenkinsfile-release, README.md, gen-jsdoc.sh, lib/infinispan.js, lib/io.js, lib/protocols.js, memory-profiling/infinispan_memory_many_get.js, memory-profiling/infinispan_memory_one_get.js, package-lock.json, package.json, smoke-tests.sh, spec-manual/infinispan_manual_stress_get_spec.js, spec-manual/infinispan_manual_stress_iterate_spec.js, spec/infinispan_cluster_spec.js, spec/infinispan_expiry_spec.js, spec/infinispan_failover_spec.js, spec/infinispan_ssl_spec.js, spec/infinispan_stress_spec.js, spec/infinispan_xsite_spec.js, spec/protocols_spec.js, spec/utils/testing.js
https://issues.jboss.org/browse/HRJS-69
https://issues.jboss.org/browse/HRJS-70
https://issues.jboss.org/browse/HRJS-71
Upgrade to Node.js 8.11.4, add Hot Rod protocol 2.9 support and switch to platform Promise module.
Also updated README on supported server and protocol versions, and added a script to generate JS docs.
=> HRJS-69 HRJS-70 HRJS-71

README.md, package-lock.json, package.json, spec/utils/test-log4js.json, spec/utils/testing.js
https://issues.jboss.org/browse/HRJS-73
Also added information around logging.
=> HRJS-73 Update dependencies

spec/infinispan_expiry_spec.js
https://issues.jboss.org/browse/HRJS-74
=> HRJS-74 Wait for expiry for longer, 1ms was too short

Jenkinsfile, lib/infinispan.js, lib/protocols.js, spec/infinispan_cluster_spec.js, spec/infinispan_json_spec.js, spec/infinispan_local_spec.js, spec/utils/testing.js
https://issues.jboss.org/browse/HRJS-76
Also add CI steps to run with these protocols.
=> HRJS-76 Fix support for Hot Rod 2.2 and 2.5 protocols

README.md, lib/protocols.js, run-testsuite.sh, spec/infinispan_expiry_spec.js, spec/infinispan_json_spec.js, spec/infinispan_local_spec.js, spec/utils/testing.js
https://issues.jboss.org/browse/HRJS-82
=> HRJS-82 Listener event converter

Jenkinsfile, run-servers.sh
* remove quotes from port parameter
=> Fix run-servers.sh

Jenkinsfile, Jenkinsfile-release, README.md, lib/codec.js, lib/io.js, lib/protocols.js, run-servers.sh, run-testsuite.sh, spec/configs/infinispan-clustered.xml, spec/configs/infinispan-ssl.xml, spec/configs/infinispan-xsite-EARTH.xml, spec/configs/infinispan-xsite-MOON.xml, spec/configs/infinispan.xml, spec/infinispan_cluster_spec.js, spec/infinispan_expiry_spec.js, spec/infinispan_failover_listener_spec.js, spec/infinispan_failover_spec.js, spec/infinispan_json_spec.js, spec/infinispan_local_spec.js, spec/infinispan_xsite_spec.js, spec/utils/testing.js, spec/utils/typed-null-return.js
* Removes protocol version checks for under 2.9
* Upgrades to 12.1.2.Final
* Includes review from @danberindei and @tristantarrant
=> Auth review and test fixes

run-servers.sh
* Override DOWNLOAD_URL to make possible download upstream/downstream version
* Fix binding servers
=> Fix binding servers

lib/codec.js, lib/protocols.js, spec/protostream_spec.js
I have done some refactoring in the code to have the code.
=> code-refactored

lib/codec.js, spec/protostream_spec.js
Added the support of query with projection.
=> Added support of query with projection

lib/codec.js, spec/codec_spec.js
Correct limit for 32 bit int is 2^32
short is 2^16
=> Fixed upper limit for int and short

documentation/asciidoc/topics/attributes/community-attributes.adoc, documentation/asciidoc/topics/code_examples/queries.js, documentation/asciidoc/topics/proc_configuring_connections.adoc, documentation/asciidoc/topics/ref_client_usage.adoc
example and documentation for queries
=> doc and example for queries

spec/configs/infinispan-xsite-EARTH.xml, spec/configs/infinispan-xsite-MOON.xml, spec/infinispan_ssl_spec.js
Fix for #108 
some jgroups options are no more available
+ added  flexibility to error msg assertion
=> fixed testsuite. Fixes #108

package-lock.json, package.json, run-servers.sh, spec/configs/clean/infinispan.xml, spec/configs/infinispan-clustered.xml, spec/configs/infinispan-ssl.xml, spec/configs/infinispan-xsite-EARTH.xml, spec/configs/infinispan-xsite-MOON.xml, spec/configs/infinispan.xml, spec/utils/testing.js
fixes #80  and bumps some packages to newer version
=> packages updates. Fixes #80

package-lock.json
=> Updated cross-spawn, requirejs
